export const productFormFields = [
  {
    label: "Thumbnail",
    name: "thumbnail",
    type: "text",
    placeholder: "",
    required: true,
  },
  {
    label: "Parent Category",
    name: "parentCategory",
    type: "select",
    placeholder: "Select category",
    required: true,
  },
  {
    label: "Name",
    name: "name",
    type: "text",
    placeholder: "Enter product name",
    required: true,
  },
  {
    label: "Price",
    name: "price",
    type: "number",
    placeholder: "Enter product price",
    required: true,
  },
  {
    label: "Available Quantity",
    name: "quantity",
    type: "number",
    placeholder: "Enter available quantity",
    required: true,
  },
  {
    label: "Description",
    name: "description",
    type: "textarea",
    placeholder: "Enter product description",
    required: true,
  },
  {
    label: "Status",
    name: "status",
    type: "select",
    placeholder: "Select status",
    options: [
      { value: "active", label: "Active" },
      { value: "inactive", label: "Inactive" },
    ],
    required: true,
  },
  {
    label: "Shop",
    name: "shop",
    type: "text",
    placeholder: "Enter shop name",
  },
  {
    label: "Author",
    name: "author",
    type: "text",
    placeholder: "Enter author name",
  },
  {
    label: "Date",
    name: "date",
    type: "date",
    placeholder: "Select date",
  },
  {
    label: "Dimensions (cm x cm)",
    name: "dimensions",
    type: "text",
    placeholder: "cm x cm",
  },
  {
    label: "Frame",
    name: "frame",
    type: "text",
    placeholder: "Enter frame details",
  },
];
